/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "DevLogging description": {                      "en": "Developer Logging",                               "de": "Entwicklerprotokollierung",                       "ru": "Ведение журнала разработчика",                    "pt": "Registro do desenvolvedor",                       "nl": "Developer Logging",                               "fr": "Journalisation de développeur",                   "it": "Registrazione degli sviluppatori",                "es": "Registro de desarrollador",                       "pl": "Logowanie dewelopera",                            "zh-cn": "开发人员记录"},
    "DevMode description": {                         "en": "Development Mode",                                "de": "Entwicklungsmodus",                               "ru": "Режим разработки",                                "pt": "Modo de desenvolvimento",                         "nl": "Ontwikkelmodus",                                  "fr": "Mode de développement",                           "it": "Modalità di sviluppo",                            "es": "Modo de desarrollo",                              "pl": "Tryb rozwoju",                                    "zh-cn": "发展模式"},
    "USBDevice": {                                   "en": "Example : /dev/ttyUSB0",                          "de": "Beispiel: / dev / ttyUSB0",                       "ru": "Пример: / dev / ttyUSB0",                         "pt": "Exemplo: / dev / ttyUSB0",                        "nl": "Voorbeeld: / dev / ttyUSB0",                      "fr": "Exemple: / dev / ttyUSB0",                        "it": "Esempio: / dev / ttyUSB0",                        "es": "Ejemplo: / dev / ttyUSB0",                        "pl": "Przykład: / dev / ttyUSB0",                       "zh-cn": "示例：/ dev / ttyUSB0"},
    "byTCPIP description": {                         "en": "Connect by TCP/IP",                               "de": "Verbinden Sie sich über TCP / IP",                "ru": "Подключение по TCP / IP",                         "pt": "Conecte-se por TCP / IP",                         "nl": "Verbind via TCP / IP",                            "fr": "Se connecter par TCP / IP",                       "it": "Connetti tramite TCP / IP",                       "es": "Conectar por TCP / IP",                           "pl": "Połącz przez TCP / IP",                           "zh-cn": "通过TCP / IP连接"},
    "byUSB description": {                           "en": "Connect by USB",                                  "de": "Verbindung über USB",                             "ru": "Подключить по USB",                               "pt": "Conecte por USB",                                 "nl": "Verbind via USB",                                 "fr": "Connecter par USB",                               "it": "Connetti tramite USB",                            "es": "Conectar por USB",                                "pl": "Połącz przez USB",                                "zh-cn": "通过USB连接"},
    "ipaddr description": {                          "en": "IP-Adress of oT-Monitor",                         "de": "IP-Adresse des oT-Monitors",                      "ru": "IP-адрес ОТ-Монитор",                             "pt": "Endereço IP do oT-Monitor",                       "nl": "IP-adres van oT-Monitor",                         "fr": "Adresse IP d'OT-Monitor",                         "it": "Indirizzo IP di oT-Monitor",                      "es": "Dirección IP de oT-Monitor",                      "pl": "Adres IP monitora oT",                            "zh-cn": "oT-Monitor的IP地址"},
    "opentherm adapter settings": {                  "en": "Opentherm setting",                               "de": "Opentherm-Einstellung",                           "ru": "Настройка Opentherm",                             "pt": "Opentherm setting",                               "nl": "Opentherm-instelling",                            "fr": "Réglage opentherm",                               "it": "Impostazione Opentherm",                          "es": "Ajuste de opentherm",                             "pl": "Ustawienie Opentherm",                            "zh-cn": "Opentherm设置"},
    "port description": {                            "en": "Port of oT-Monitor",                              "de": "Port des oT-Monitors",                            "ru": "Порт ОТ-Монитор",                                 "pt": "Porto de oT-Monitor",                             "nl": "Haven van oT-Monitor",                            "fr": "Port d'OT-Monitor",                               "it": "Porta di oT-Monitor",                             "es": "Puerto de oT-monitor",                            "pl": "Port monitora oT",                                "zh-cn": "oT-Monitor端口"},
    "usb": {                                         "en": "USB Device",                                      "de": "USB Gerät",                                       "ru": "USB-устройство",                                  "pt": "Dispositivo USB",                                 "nl": "USB-apparaat",                                    "fr": "Périphérique USB",                                "it": "Dispositivo USB",                                 "es": "Dispositivo USB",                                 "pl": "Urządzenie USB",                                  "zh-cn": "USB设备"},
};